# Generated by Django 3.2.19 on 2023-06-13 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20230613_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_email_address',
        ),
    ]
