# Generated by Django 3.2.19 on 2023-05-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20230522_1455'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packages',
            new_name='Package',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
